name: VitalHeal
version: @version@
main: com.tamrielnetwork.vitalheal.VitalHeal
api-version: 1.17
authors: [ Tamriel Network ]
website: https://tamriel.site
description: Gives players the ability to heal.
commands:
  vitalheal:
    description: "Main command"
    usage: "/vitalheal"
permissions:
  vitalheal.heal:
    description: "Permission to heal yourself"
    default: op
  vitalheal.heal.others:
    description: "Permission to heal other players"
    default: op